/**
 * Trade recommendation engine.
 *
 * Converts a raw Signal (generated by the scanner) into a concrete TradeIdea
 * with entry price, stop price, target price, risk-based quantity, and R:R ratio.
 *
 * Stop / target sourcing (in priority order):
 *   1. Strategy decision's stopPct / targetPct (if the strategy provides them).
 *   2. ATR-based fallback: stop = entry - atrMultiple * ATR(14),
 *      target = entry + atrTarget * ATR(14).
 *
 * Entry price = last close (the signal bar's close).
 * Actual fill will happen at next bar's open; the caller should note this is
 * approximate and mark it as a "pending fill at next open" in the UI.
 *
 * Pure function (no I/O, no DB). Called by /api/scan after scanning.
 */

import type { Bar, Signal, TradeIdea } from '@/core/types';
import { compute } from '@/core/indicators/registry';
import { riskBasedQty, type SizingConfig, DEFAULT_SIZING } from '@/core/risk/sizing';
import type { StrategyDecision } from '@/core/strategy/Strategy';

export interface RecommendConfig extends Partial<SizingConfig> {
  /** ATR multiplier for stop distance when strategy doesn't supply stopPct. Default 2. */
  atrStopMultiple?:   number;
  /** ATR multiplier for target distance when strategy doesn't supply targetPct. Default 3. */
  atrTargetMultiple?: number;
  /** ATR period. Default 14. */
  atrPeriod?:         number;
}

/**
 * Build a TradeIdea from a Signal, the symbol's bars, the strategy decision
 * (for stopPct / targetPct), and optional config.
 *
 * Returns null if we cannot compute a meaningful stop (e.g. not enough bars for ATR).
 */
export function recommendTrade(
  signal:   Signal,
  bars:     readonly Bar[],
  decision: Pick<StrategyDecision, 'stopPct' | 'targetPct'>,
  cfg:      RecommendConfig = {},
): TradeIdea | null {
  if (bars.length < 2) return null;

  const {
    equity          = DEFAULT_SIZING.equity,
    riskPct         = DEFAULT_SIZING.riskPct,
    atrStopMultiple   = 2,
    atrTargetMultiple = 3,
    atrPeriod         = 14,
  } = cfg;

  const lastBar    = bars[bars.length - 1];
  const entryPrice = lastBar.close;

  // Compute ATR for fallback stop/target
  let atrValue = NaN;
  if (bars.length >= atrPeriod + 1) {
    try {
      const atrArr = compute('atr', bars as Bar[], { period: atrPeriod }) as number[];
      const last   = atrArr[atrArr.length - 1];
      if (Number.isFinite(last)) atrValue = last;
    } catch {
      // not enough bars - atrValue stays NaN
    }
  }

  // Resolve stop price
  let stopPrice: number;
  if (decision.stopPct != null && decision.stopPct > 0) {
    stopPrice = signal.side === 'long'
      ? entryPrice * (1 - decision.stopPct)
      : entryPrice * (1 + decision.stopPct);
  } else if (Number.isFinite(atrValue)) {
    stopPrice = signal.side === 'long'
      ? entryPrice - atrStopMultiple * atrValue
      : entryPrice + atrStopMultiple * atrValue;
  } else {
    return null; // cannot size without a stop
  }

  // Resolve target price
  let targetPrice: number;
  if (decision.targetPct != null && decision.targetPct > 0) {
    targetPrice = signal.side === 'long'
      ? entryPrice * (1 + decision.targetPct)
      : entryPrice * (1 - decision.targetPct);
  } else if (Number.isFinite(atrValue)) {
    targetPrice = signal.side === 'long'
      ? entryPrice + atrTargetMultiple * atrValue
      : entryPrice - atrTargetMultiple * atrValue;
  } else {
    // No target: set a 1.5 R:R target based on stop distance
    const stopDist = Math.abs(entryPrice - stopPrice);
    targetPrice = signal.side === 'long'
      ? entryPrice + 1.5 * stopDist
      : entryPrice - 1.5 * stopDist;
  }

  // Risk-based quantity
  let sizing: ReturnType<typeof riskBasedQty>;
  try {
    sizing = riskBasedQty({ equity, riskPct, entryPrice, stopPrice });
  } catch {
    return null;
  }

  const { qty, riskAmount } = sizing;
  const stopDist   = Math.abs(entryPrice - stopPrice);
  const targetDist = Math.abs(targetPrice - entryPrice);
  const rewardAmount = qty * targetDist;
  const rr           = stopDist > 0 ? targetDist / stopDist : 0;

  return {
    symbol:       signal.symbol,
    strategyId:   signal.strategyId,
    side:         signal.side === 'flat' ? 'long' : signal.side,
    // currency is unknown at this layer; the caller (api/scan route) overwrites
    // this with the correct value from the symbols table.
    currency:     'USD',
    entryPrice,
    stopPrice,
    targetPrice,
    qty,
    riskAmount,
    rewardAmount,
    rr,
    reason:       signal.reason,
    time:         signal.time,
  };
}
